package com.tuoke.security.entity;

/**
 * Transaction实体类，由Mybatis generator自动生成
 */
public class Transaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.id
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.trade_id
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    private Integer tradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.version
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.security_code
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    private String securityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.quantity
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.action
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.trade_direction
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    private String tradeDirection;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.id
     *
     * @return the value of transaction.id
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.id
     *
     * @param id the value for transaction.id
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.trade_id
     *
     * @return the value of transaction.trade_id
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.trade_id
     *
     * @param tradeId the value for transaction.trade_id
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.version
     *
     * @return the value of transaction.version
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.version
     *
     * @param version the value for transaction.version
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.security_code
     *
     * @return the value of transaction.security_code
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.security_code
     *
     * @param securityCode the value for transaction.security_code
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode == null ? null : securityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.quantity
     *
     * @return the value of transaction.quantity
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.quantity
     *
     * @param quantity the value for transaction.quantity
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.action
     *
     * @return the value of transaction.action
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.action
     *
     * @param action the value for transaction.action
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.trade_direction
     *
     * @return the value of transaction.trade_direction
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public String getTradeDirection() {
        return tradeDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.trade_direction
     *
     * @param tradeDirection the value for transaction.trade_direction
     *
     * @mbg.generated Thu Apr 15 20:53:45 CST 2021
     */
    public void setTradeDirection(String tradeDirection) {
        this.tradeDirection = tradeDirection == null ? null : tradeDirection.trim();
    }

    public Transaction(Integer id, Integer tradeId, Integer version, String securityCode, Integer quantity, String action, String tradeDirection) {
        this.id = id;
        this.tradeId = tradeId;
        this.version = version;
        this.securityCode = securityCode;
        this.quantity = quantity;
        this.action = action;
        this.tradeDirection = tradeDirection;
    }

    @Override
    public String toString() {
        return "Transaction{" +
                "id=" + id +
                ", tradeId=" + tradeId +
                ", version=" + version +
                ", securityCode='" + securityCode + '\'' +
                ", quantity=" + quantity +
                ", action='" + action + '\'' +
                ", tradeDirection='" + tradeDirection + '\'' +
                '}';
    }
}